# Generated by Django 3.2.18 on 2023-04-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20230419_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='table',
            field=models.CharField(choices=[('1', 'Table1'), ('2', 'Table2'), ('3', 'Table3'), ('4', 'Table4'), ('5', 'Table5')], max_length=2),
        ),
    ]
