# Generated by Django 3.2.18 on 2023-04-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_date_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='table',
            field=models.CharField(max_length=20),
        ),
    ]
