# Generated by Django 3.2.18 on 2023-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_date_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
