# Generated by Django 3.2.18 on 2023-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_date_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='table',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
