# Generated by Django 3.2.18 on 2023-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_date_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='table',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'Table1'), (2, 'Table2'), (3, 'Table3'), (4, 'Table4'), (5, 'Table5')], default=0),
        ),
    ]
