# Generated by Django 3.2.18 on 2023-04-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_date_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('reservation_date', 'table')},
        ),
    ]
